/**
 * Catálogo de emojis (curado, categorizado, com termos de busca pt-BR).
 * Usado pelo seletor único (aba Emojis) e pela galeria geral.
 */
export interface ItemEmoji { e: string; cat: string; termos: string }

export const CATEGORIAS_EMOJI = [
  'Rostos', 'Gestos', 'Símbolos', 'Saúde', 'Natureza', 'Comida', 'Lugares', 'Objetos', 'Datas',
];

export const EMOJIS: ItemEmoji[] = [
  // Rostos
  { e: '😀', cat: 'Rostos', termos: 'sorriso feliz rosto' },
  { e: '😊', cat: 'Rostos', termos: 'feliz simpático' },
  { e: '😄', cat: 'Rostos', termos: 'alegre rindo' },
  { e: '😁', cat: 'Rostos', termos: 'sorriso dentes' },
  { e: '😂', cat: 'Rostos', termos: 'rindo lágrima' },
  { e: '🥰', cat: 'Rostos', termos: 'amor carinho corações' },
  { e: '😍', cat: 'Rostos', termos: 'apaixonado coração' },
  { e: '😎', cat: 'Rostos', termos: 'óculos legal' },
  { e: '🤔', cat: 'Rostos', termos: 'pensando dúvida' },
  { e: '🙂', cat: 'Rostos', termos: 'leve sorriso' },
  { e: '😉', cat: 'Rostos', termos: 'piscadela' },
  { e: '😢', cat: 'Rostos', termos: 'triste choro' },
  { e: '😡', cat: 'Rostos', termos: 'bravo raiva' },
  { e: '😴', cat: 'Rostos', termos: 'dormindo sono' },
  { e: '🥳', cat: 'Rostos', termos: 'festa comemoração' },
  { e: '🤩', cat: 'Rostos', termos: 'estrelas animado' },

  // Gestos & pessoas
  { e: '👍', cat: 'Gestos', termos: 'joia positivo curtir ok' },
  { e: '👎', cat: 'Gestos', termos: 'negativo ruim' },
  { e: '👏', cat: 'Gestos', termos: 'palmas aplauso' },
  { e: '🙏', cat: 'Gestos', termos: 'obrigado oração por favor' },
  { e: '🤝', cat: 'Gestos', termos: 'aperto de mão acordo parceria' },
  { e: '✌️', cat: 'Gestos', termos: 'paz vitória' },
  { e: '👋', cat: 'Gestos', termos: 'olá tchau aceno' },
  { e: '💪', cat: 'Gestos', termos: 'força braço' },
  { e: '🙌', cat: 'Gestos', termos: 'mãos comemorar' },
  { e: '👌', cat: 'Gestos', termos: 'ok certo' },
  { e: '🫶', cat: 'Gestos', termos: 'coração mãos amor' },
  { e: '👨‍👩‍👧‍👦', cat: 'Gestos', termos: 'família' },
  { e: '🧑‍🦽', cat: 'Gestos', termos: 'cadeira de rodas acessibilidade pcd' },
  { e: '👶', cat: 'Gestos', termos: 'bebê criança' },
  { e: '🧓', cat: 'Gestos', termos: 'idoso terceira idade' },
  { e: '👮', cat: 'Gestos', termos: 'policial guarda segurança' },

  // Símbolos
  { e: '✅', cat: 'Símbolos', termos: 'check certo aprovado ok' },
  { e: '❌', cat: 'Símbolos', termos: 'errado cancelar x' },
  { e: '⚠️', cat: 'Símbolos', termos: 'atenção aviso alerta' },
  { e: '❗', cat: 'Símbolos', termos: 'importante exclamação' },
  { e: '❓', cat: 'Símbolos', termos: 'dúvida pergunta' },
  { e: '💡', cat: 'Símbolos', termos: 'ideia lâmpada dica' },
  { e: '🔔', cat: 'Símbolos', termos: 'sino aviso notificação' },
  { e: '📌', cat: 'Símbolos', termos: 'fixar pin destaque' },
  { e: '📎', cat: 'Símbolos', termos: 'anexo clipe' },
  { e: '🔗', cat: 'Símbolos', termos: 'link corrente' },
  { e: '📋', cat: 'Símbolos', termos: 'lista prancheta' },
  { e: '⭐', cat: 'Símbolos', termos: 'estrela destaque favorito' },
  { e: '🚫', cat: 'Símbolos', termos: 'proibido bloqueado' },
  { e: '♻️', cat: 'Símbolos', termos: 'reciclagem sustentável' },
  { e: '🆕', cat: 'Símbolos', termos: 'novo new' },
  { e: '🔒', cat: 'Símbolos', termos: 'cadeado seguro privacidade' },

  // Saúde
  { e: '🏥', cat: 'Saúde', termos: 'hospital posto saúde' },
  { e: '💉', cat: 'Saúde', termos: 'vacina seringa' },
  { e: '💊', cat: 'Saúde', termos: 'remédio farmácia' },
  { e: '🩺', cat: 'Saúde', termos: 'médico estetoscópio consulta' },
  { e: '🚑', cat: 'Saúde', termos: 'ambulância samu' },
  { e: '❤️', cat: 'Saúde', termos: 'coração saúde amor' },
  { e: '🦷', cat: 'Saúde', termos: 'dente odontológico' },
  { e: '🧬', cat: 'Saúde', termos: 'dna saúde' },

  // Natureza
  { e: '🌳', cat: 'Natureza', termos: 'árvore meio ambiente' },
  { e: '🌱', cat: 'Natureza', termos: 'planta muda crescer' },
  { e: '🍃', cat: 'Natureza', termos: 'folha verde natureza' },
  { e: '💧', cat: 'Natureza', termos: 'água gota saneamento' },
  { e: '☀️', cat: 'Natureza', termos: 'sol clima tempo' },
  { e: '🌧️', cat: 'Natureza', termos: 'chuva clima' },
  { e: '🔥', cat: 'Natureza', termos: 'fogo bombeiro incêndio' },
  { e: '🐾', cat: 'Natureza', termos: 'animais pata pet zoonoses' },
  { e: '🐕', cat: 'Natureza', termos: 'cachorro animal' },
  { e: '🐄', cat: 'Natureza', termos: 'vaca gado agropecuária' },
  { e: '🌾', cat: 'Natureza', termos: 'trigo agricultura plantação' },
  { e: '🚜', cat: 'Natureza', termos: 'trator rural fazenda' },

  // Comida
  { e: '🍎', cat: 'Comida', termos: 'maçã fruta alimentação' },
  { e: '🥗', cat: 'Comida', termos: 'salada alimentação saudável' },
  { e: '🍞', cat: 'Comida', termos: 'pão alimento' },
  { e: '🍲', cat: 'Comida', termos: 'comida prato refeição merenda' },
  { e: '💦', cat: 'Comida', termos: 'água potável' },

  // Lugares & transporte
  { e: '🏛️', cat: 'Lugares', termos: 'prefeitura governo sede' },
  { e: '🏫', cat: 'Lugares', termos: 'escola educação creche' },
  { e: '🏠', cat: 'Lugares', termos: 'casa habitação moradia' },
  { e: '🏢', cat: 'Lugares', termos: 'prédio órgão secretaria' },
  { e: '📍', cat: 'Lugares', termos: 'local endereço ponto pin' },
  { e: '🗺️', cat: 'Lugares', termos: 'mapa localização' },
  { e: '🚌', cat: 'Lugares', termos: 'ônibus transporte' },
  { e: '🚗', cat: 'Lugares', termos: 'carro veículo' },
  { e: '🚧', cat: 'Lugares', termos: 'obras construção trânsito' },
  { e: '🚦', cat: 'Lugares', termos: 'semáforo trânsito' },
  { e: '🚸', cat: 'Lugares', termos: 'faixa pedestres crianças' },
  { e: '🚮', cat: 'Lugares', termos: 'lixo coleta limpeza' },

  // Objetos
  { e: '📞', cat: 'Objetos', termos: 'telefone ligar contato' },
  { e: '📧', cat: 'Objetos', termos: 'email correio' },
  { e: '📱', cat: 'Objetos', termos: 'celular app aplicativo' },
  { e: '💻', cat: 'Objetos', termos: 'computador notebook' },
  { e: '📄', cat: 'Objetos', termos: 'documento papel' },
  { e: '📑', cat: 'Objetos', termos: 'documentos abas' },
  { e: '📚', cat: 'Objetos', termos: 'livros biblioteca' },
  { e: '🔑', cat: 'Objetos', termos: 'chave acesso senha' },
  { e: '💳', cat: 'Objetos', termos: 'cartão pagamento' },
  { e: '💰', cat: 'Objetos', termos: 'dinheiro finanças' },
  { e: '💵', cat: 'Objetos', termos: 'dinheiro nota' },
  { e: '📊', cat: 'Objetos', termos: 'gráfico dados estatística' },
  { e: '📈', cat: 'Objetos', termos: 'crescimento alta indicador' },
  { e: '⚖️', cat: 'Objetos', termos: 'justiça balança lei' },
  { e: '🛠️', cat: 'Objetos', termos: 'ferramentas manutenção obras' },
  { e: '🔧', cat: 'Objetos', termos: 'chave de boca reparo' },
  { e: '🏆', cat: 'Objetos', termos: 'troféu prêmio esporte' },
  { e: '🥇', cat: 'Objetos', termos: 'medalha ouro' },
  { e: '⚽', cat: 'Objetos', termos: 'futebol bola esporte' },
  { e: '🎭', cat: 'Objetos', termos: 'teatro cultura arte' },
  { e: '🎨', cat: 'Objetos', termos: 'arte cultura pintura' },
  { e: '🎵', cat: 'Objetos', termos: 'música som' },
  { e: '📷', cat: 'Objetos', termos: 'câmera foto' },
  { e: '🎥', cat: 'Objetos', termos: 'vídeo filmagem' },
  { e: '🔍', cat: 'Objetos', termos: 'busca lupa pesquisa' },
  { e: '🗳️', cat: 'Objetos', termos: 'urna voto eleição enquete' },
  { e: '📣', cat: 'Objetos', termos: 'megafone aviso campanha' },

  // Datas / marcos
  { e: '📅', cat: 'Datas', termos: 'calendário data agenda' },
  { e: '📆', cat: 'Datas', termos: 'calendário evento' },
  { e: '🗓️', cat: 'Datas', termos: 'agenda calendário' },
  { e: '⏰', cat: 'Datas', termos: 'relógio horário hora' },
  { e: '🎉', cat: 'Datas', termos: 'festa comemoração evento' },
  { e: '🎗️', cat: 'Datas', termos: 'laço campanha conscientização' },
  { e: '🎀', cat: 'Datas', termos: 'laço outubro rosa' },
  { e: '💛', cat: 'Datas', termos: 'amarelo setembro coração' },
  { e: '💙', cat: 'Datas', termos: 'azul novembro coração' },
];
