/**
 * Nomes das fontes/destinações de recurso do APLIC (TCE-MT) — para apresentar
 * saldos e arrecadação por FONTE de forma legível. Cópia mínima das tabelas
 * internas DESTINACAO_RECURSO_GRUPO/ESPECIFIC (E:\\REGRAS). Atualizar se o TCE revisar.
 */

/** DRGRP_Codigo -> nome do grupo de destinação de recurso. */
export const DR_GRUPO: Record<string, string> = {
  '1': 'Recursos do Exercício Corrente',
  '2': 'Recursos de Exercícios Anteriores',
  '3': 'Recursos de Exercícios Anteriores',
  '6': 'Recursos de Outras Fontes - Exercícios Anteriores',
  '9': 'Recursos Condicionados',
};

/** DRESP_Codigo -> nome da especificação da destinação (a 'fonte de recurso'). */
export const DR_ESPECIFICACAO: Record<string, string> = {
  '00': 'Recursos Ordinários',
  '01': 'Receitas de Impostos e de Transferência de Impostos - Educação',
  '02': 'Receitas de Impostos e de Transferência de Impostos - Saúde',
  '03': 'Contribuição para o Regime Próprio de Previdência Social – RPPS (patronal, servidores e compensação financeira)',
  '04': 'Contribuição ao Programa Ensino Fundamental',
  '12': 'Serviços de Saúde',
  '14': 'Transferência de Recursos do Sistema Único de Saúde - União (até 2018)',
  '15': 'Transferência de Recursos do Fundo Nacional do Desenvolvimento da Educação - FNDE',
  '16': 'Contribuição de Intervenção do Domínio Econômico - CIDE',
  '17': 'Contribuição para o Custeio dos Serviços de Iluminação Pública - COSIP',
  '18': 'Transferências do FUNDEB - (aplicação na remuneração dos profissionais do Magistério em efetivo exercício na Educação Básica)',
  '19': 'Transferências do FUNDEB - (aplicação em outras despesas da Educação Básica)',
  '21': 'Transferências de Convênios – Assistência Social',
  '22': 'Transferências de Convênios ou Contratos de Repasse - Educação ',
  '23': 'Transferências de Convênios ou Contratos de Repasse - Saúde',
  '24': 'Outras Transferências de Convênios ou Contratos de Repasse da União (não relacionados à educação/saúde/assistência social)',
  '25': 'Demais Recursos Vinculados Destinados à Educação',
  '26': 'Demais Recursos Vinculados Destinados à Saúde',
  '27': 'Demais Recursos Vinculados Destinados Assistência Social',
  '29': 'Transferência de Recursos do Fundo Nacional de Assistência Social – FNAS',
  '30': 'Recursos provenientes do Fundo de Transporte e Habitação – FETHAB',
  '31': 'Transferências do FUNDEB – Complementação da União',
  '32': 'Operações de Crédito Vinculadas à Educação',
  '33': 'Outras Transferências de Convênios ou Contratos de Repasse do Estado (não relacionados à educação/saúde/assistência social)',
  '34': 'Transferência da União Referente a Royalties do Petróleo',
  '35': 'Transferência dos Estados Referente a Royalties do Petróleo',
  '36': 'Recursos Vinculados ao Trânsito',
  '37': 'Transferência da União referente à Cessão Onerosa - Pré-Sal - Lei n. 13.885/2019',
  '41': 'Serviços Hospitalares',
  '42': 'Transferência de Recursos do Sistema Único de Saúde – SUS – Estado',
  '43': 'Transferência de recursos do Estado para ações de Assistência Social',
  '44': 'Operações de Crédito Vinculadas à Saúde',
  '45': 'Transferências Fundo a Fundo de Recursos do SUS provenientes dos Governos Municipais',
  '46': 'Transferências Fundo a Fundo de Recursos do SUS provenientes do Governo Federal - Bloco de Manutenção das Ações e Serviços Públicos de Saúde',
  '47': 'Transferências Fundo a Fundo de Recursos do SUS provenientes do Governo Federal - Bloco de Estruturação da Rede de Serviços Públicos de Saúde',
  '50': 'Recursos do Regime Próprio de Previdência (RPPS)',
  '500': 'Recursos não Vinculados de Impostos',
  '501': 'Outros Recursos não Vinculados',
  '502': 'Recursos não vinculados da compensação de impostos',
  '503': 'Apoio financeiro da União em decorrência de estado de calamidade pública',
  '51': 'Recursos do Fundo Financeiro',
  '52': 'Recursos do Fundo Previdenciário',
  '53': 'Recursos da Taxa de Administração',
  '54': 'Recursos do Superávit da Taxa de Administração',
  '540': 'Transferências do FUNDEB Impostos e Transferências de Impostos',
  '541': 'Transferências do FUNDEB Complementação da União VAAF',
  '542': 'Transferências do FUNDEB Complementação da União VAAT',
  '543': 'Transferências do FUNDEB Complementação da União VAAR',
  '544': 'Recursos de Precatórios do FUNDEF',
  '545': 'Recursos de Precatórios do FUNDEB (2007- 2020)',
  '546': 'Transferências do FUNDEB - Complementação da União - ETI',
  '550': 'Transferência do Salário Educação',
  '551': 'Transferências de Recursos do FNDE referentes ao Programa Dinheiro Direto na Escola (PDDE)',
  '552': 'Transferências de Recursos do FNDE referentes ao Programa Nacional de Alimentação Escolar (PNAE)',
  '553': 'Transferências de Recursos do FNDE Referentes ao Programa Nacional de Apoio ao Transporte Escolar (PNATE)',
  '569': 'Outras Transferências de Recursos do FNDE',
  '570': 'Transferências do Governo Federal referentes a Convênios e Instrumentos Congêneres vinculados à Educação',
  '571': 'Transferências do Estado referentes a Convênios e Instrumentos Congêneres vinculados à Educação',
  '572': 'Transferências de Municípios referentes a Convênios e Instrumentos Congêneres vinculados à Educação',
  '573': 'Royalties e Participação Especial de Petróleo e Gás Natural Vinculados à Educação - Lei nº 12.858/2013',
  '574': 'Operações de Crédito Vinculadas à Educação',
  '575': 'Outras Transferências de Convênios e Instrumentos Congêneres vinculados à Educação',
  '576': 'Transferências de Recursos dos Estados para programas de educação',
  '599': 'Outros Recursos Vinculados à Educação',
  '600': 'Transferências Fundo a Fundo de Recursos do SUS provenientes do Governo Federal - Bloco de Manutenção das Ações e Serviços Públicos de Saúde',
  '601': 'Transferências Fundo a Fundo de Recursos do SUS provenientes do Governo Federal - Bloco de Estruturação da Rede de Serviços Públicos de Saúde',
  '602': 'Transferências Fundo a Fundo de Recursos do SUS provenientes do Governo Federal - Bloco de Manutenção das Ações e Serviços Públicos de Saúde - Recursos destinados ao enfrentamento da COVID-19 no bojo da ação 21C0.',
  '603': 'Transferências Fundo a Fundo de Recursos do SUS provenientes do Governo Federal - Bloco de Estruturação da Rede de Serviços Públicos de Saúde - Recursos destinados ao enfrentamento da COVID-19 no bojo da ação 21C0.',
  '604': 'Transferências provenientes do Governo Federal destinadas ao vencimento dos agentes comunitários de saúde e dos agentes de combate às endemias',
  '605': 'Assistência financeira da União destinada à complementação ao pagamento dos pisos salariais para profissionais da enfermagem',
  '621': 'Transferências Fundo a Fundo de Recursos do SUS provenientes do Governo Estadual',
  '622': 'Transferências Fundo a Fundo de Recursos do SUS provenientes dos Governos Municipais',
  '631': 'Transferências do Governo Federal referentes a Convênios e Instrumentos Congêneres vinculados à Saúde',
  '632': 'Transferências do Estado referentes a Convênios e Instrumentos Congêneres vinculados à Saúde',
  '633': 'Transferências de Municípios referentes a Convênios Instrumentos Congêneres vinculados à Saúde',
  '634': 'Operações de Crédito vinculadas à Saúde',
  '635': 'Royalties e Participação Especial de Petróleo e Gás Natural vinculados à Saúde - Lei nº 12.858/2013',
  '636': 'Outras Transferências de Convênios e Instrumentos Congêneres vinculados à Saúde',
  '659': 'Outros Recursos Vinculados à Saúde',
  '660': 'Transferência de Recursos do Fundo Nacional de Assistência Social - FNAS',
  '661': 'Transferência de Recursos dos Fundos Estaduais de Assistência Social',
  '662': 'Transferências de Recursos dos Fundos Municipais de Assistência Social',
  '665': 'Transferências de Convênios e Instrumentos Congêneres vinculados à Assistência Social',
  '669': 'Outros Recursos Vinculados à Assistência Social',
  '70': 'Recursos de depósitos judiciais – Lides das quais o ente faz parte',
  '700': 'Outras Transferências de Convênios ou Instrumentos Congêneres da União',
  '701': 'Outras Transferências de Convênios ou Instrumentos Congêneres dos Estados',
  '702': 'Outras Transferências de Convênios ou Instrumentos Congêneres dos Municípios',
  '703': 'Outras Transferências de Convênios ou Instrumentos Congêneres de outras Entidades',
  '704': 'Transferências da União Referentes a Compensações Financeiras pela Exploração de Recursos Naturais',
  '705': 'Transferências dos Estados Referentes a Compensações Financeiras pela Exploração de Recursos Naturais',
  '706': 'Transferência Especial da União',
  '707': 'Transferências da União - inciso I do art. 5º da Lei Complementar 173/2020',
  '708': 'Transferência da União Referente à Compensação Financeira de Recursos Minerais',
  '709': 'Transferência da União referente à Compensação Financeira de Recursos Hídricos',
  '71': 'Recursos de depósitos judiciais – Lides das quais o ente não faz parte',
  '710': 'Transferência Especial dos Estados',
  '711': 'Demais Transferências Obrigatórias não Decorrentes de Repartições de Receitas',
  '712': 'Transferências Fundo a Fundo de Recursos do Fundo Penitenciário – FUNPEN',
  '713': 'Transferências Fundo a Fundo de Recursos do Fundo de Segurança Pública – FSP',
  '714': 'Transferências Fundo a Fundo de Recursos do Fundo de Amparo ao Trabalhador – FAT',
  '715': 'Transferências Destinadas ao Setor Cultural - LC nº 195/2022 - Art. 5º Audiovisual',
  '716': 'Transferências Destinadas ao Setor cultural - LC nº 195/2022 - Art. 8º Demais Setores da Cultura',
  '717': 'Assistência Financeira Transporte Coletivo Art. 5º, Inciso IV, EC nº 123/2022',
  '718': 'Auxílio Financeiro Outorga Crédito Tributário ICMS - Art. 5º, Inciso V, EC nº 123/2022',
  '719': 'Transferências da Política Nacional Aldir Blanc de Fomento à Cultura - Lei nº 14.399/2022',
  '72': 'Outras vinculações de transferências',
  '720': 'Transferências da União Referentes às participações na exploração de Petróleo e Gás Natural destinadas ao FEP - Lei 9.478/1997',
  '721': 'Transferências da União Referentes a Cessão Onerosa de Petróleo – Lei nº 13.885/2019',
  '747': 'Outras vinculações de transferências da União',
  '748': 'Outras vinculações de transferências dos Estados',
  '749': 'Outras vinculações de transferências',
  '750': 'Recursos da Contribuição de Intervenção no Domínio Econômico - CIDE',
  '751': 'Recursos da Contribuição para o Custeio do Serviço de Iluminação Pública - COSIP',
  '752': 'Recursos Vinculados ao Trânsito',
  '753': 'Recursos Provenientes de Taxas, Contribuições e Preços Públicos',
  '754': 'Recursos de Operações de Crédito',
  '755': 'Recursos de Alienação de Bens/Ativos - Administração Direta',
  '756': 'Recursos de Alienação de Bens/Ativos - Administração Indireta',
  '757': 'Recursos de Depósitos Judiciais - Lides das quais o Ente faz parte',
  '758': 'Recursos de Depósitos Judiciais - Lides das quais o Ente não faz parte',
  '759': 'Recursos Vinculados a Fundos',
  '760': 'Recursos de Emolumentos, Taxas e Custas',
  '761': 'Recursos Vinculados ao Fundo de Combate e Erradicação da Pobreza',
  '762': 'Recursos de Alienação de Ativos - Cessão de Direitos Creditórios',
  '799': 'Outras Vinculações Legais',
  '80': 'Consignações e retenções',
  '800': 'Recursos Vinculados ao RPPS - Fundo em Capitalização (Plano Previdenciário)',
  '801': 'Recursos Vinculados ao RPPS - Fundo em Repartição (Plano Financeiro)',
  '802': 'Recursos Vinculados ao RPPS - Taxa de Administração',
  '803': 'Recursos Vinculados ao Sistema de Proteção Social dos Militares (SPSM)',
  '804': 'Demais Recursos Previdenciários',
  '81': 'Recursos extraorçamentários',
  '82': 'Demais Recursos Vinculados (não relacionados à Educação/ Saúde/ Assist. Social)',
  '83': 'Recursos extraorçamentários vinculados a precatórios',
  '84': 'Recursos extraorçamentários vinculados a depósitos judiciais',
  '860': 'Recursos Extraorçamentários Vinculados a Precatórios',
  '861': 'Recursos Extraorçamentários Vinculados a Depósitos Judiciais',
  '862': 'Recursos de Depósitos de Terceiros',
  '869': 'Outros recursos extraorçamentários',
  '880': 'Recursos Próprios dos Consórcios',
  '898': 'Recursos a Classificar',
  '899': 'Outros Recursos Vinculados',
  '90': 'Operações de Crédito Internas',
  '91': 'Operações de Crédito Externas',
  '92': 'Alienação de Bens',
  '93': 'Outras Receitas Não-Primárias',
  '94': 'Recursos próprios dos consórcios',
};

/** Rótulo da fonte a partir do código composto DRGRP.DRESP.DESTREC. */
export function nomeFonte(drgrp?: string | null, dresp?: string | null): string | null {
  const e = dresp ? DR_ESPECIFICACAO[dresp.replace(/^0+/, '') || dresp] ?? DR_ESPECIFICACAO[dresp] : null;
  if (e) return e;
  const g = drgrp ? DR_GRUPO[drgrp] : null;
  return g ?? null;
}
